package com.pk4us.pikachuadd

object MainConst {
    val imageList = listOf(
        R.drawable.clouds,
        R.drawable._1,
        R.drawable._2,
        R.drawable._3,
        R.drawable._4,
        R.drawable._5,
        R.drawable._6,
        R.drawable._7,
        R.drawable._8,
        R.drawable._9,
        R.drawable._10,
        R.drawable._11,
        R.drawable._12,
        R.drawable._13,
        R.drawable._14,
        R.drawable._15,
        R.drawable._16,
        R.drawable._17,
        R.drawable._18,
        R.drawable._19,
        R.drawable._20,
        R.drawable._21,
        R.drawable._22,
        R.drawable._23,
        R.drawable._24,
        R.drawable._25,
        R.drawable._26,
        R.drawable._27,
        R.drawable._28,
        R.drawable._29,
        R.drawable._30,
        R.drawable._31,
        R.drawable._32,
        R.drawable._33,
        R.drawable._34,
        R.drawable._35,
    )
    val arrayList = listOf(
        R.array.philosophy_array,
    )
}